# Generated by Django 5.2.12 on 2026-04-05 19:59

from django.db import migrations, models


def migrate_user_roles_and_approval(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    User.objects.filter(role="STAFF").update(role="STUDENT")
    User.objects.filter(is_superuser=True).update(is_approved=True)
    User.objects.filter(role="ADMIN").update(is_approved=True)


def reverse_user_roles_and_approval(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    User.objects.filter(role="STUDENT").update(role="STAFF")
    User.objects.filter(is_superuser=False).update(is_approved=False)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Determines whether the user can log in to TMS.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('TRAINER', 'Trainer'), ('STUDENT', 'Student')], db_index=True, default='STUDENT', help_text='Role assigned to the user for access control in TMS.', max_length=20),
        ),
        migrations.RunPython(migrate_user_roles_and_approval, reverse_user_roles_and_approval),
    ]
