[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install -r tms/requirements.txt"
]

[phases.build]
cmds = [] 

[start]
cmd = "cd tms && /opt/venv/bin/gunicorn tms.wsgi"