# Generated by Django 5.0.6 on 2026-04-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_studentattendance_status_workingday_and_more'),
        ('batch', '0003_batch_deleted_at_batch_is_deleted_course_deleted_at_and_more'),
        ('students', '0004_student_deleted_at_student_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentattendance',
            options={'ordering': ['-date', 'slot', 'student__name']},
        ),
        migrations.RemoveConstraint(
            model_name='studentattendance',
            name='unique_student_attendance_per_day',
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='slot',
            field=models.CharField(choices=[('1', 'Slot 1'), ('2', 'Slot 2'), ('3', 'Slot 3')], db_index=True, default='1', max_length=1),
        ),
        migrations.AddConstraint(
            model_name='studentattendance',
            constraint=models.UniqueConstraint(fields=('student', 'date', 'slot'), name='unique_student_attendance_per_slot'),
        ),
    ]
