# Generated by Django 5.2.12 on 2026-04-05 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
        ('labs', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(db_index=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='batch.batch')),
            ],
            options={
                'ordering': ['-exam_date', 'batch__name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='exams.exam')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_slots', to='labs.lab')),
            ],
            options={
                'ordering': ['exam__exam_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentExamSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='exams.examslot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_slot_assignments', to='students.student')),
            ],
            options={
                'ordering': ['student__name'],
                'constraints': [models.UniqueConstraint(fields=('student', 'exam_slot'), name='unique_student_exam_slot_assignment')],
            },
        ),
    ]
