# Generated by Django 5.2.12 on 2026-04-05 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch', '0001_initial'),
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='batch.batch')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='labs.lab')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'email'), name='unique_student_email_per_batch')],
            },
        ),
    ]
