# Generated by Codex on 2026-04-06

import django.db.models.deletion
from django.db import migrations, models


def populate_student_ug_numbers(apps, schema_editor):
    Student = apps.get_model("students", "Student")

    for student in Student.objects.filter(ug_number="").iterator():
        student.ug_number = f"UG-{student.batch_id}-{student.pk}"
        if not student.department:
            student.department = "General"
        student.save(update_fields=["ug_number", "department"])


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0002_course_and_created_by"),
        ("labs", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="unique_student_email_per_batch",
        ),
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(default="General", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="ug_number",
            field=models.CharField(db_index=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="student",
            name="lab",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="labs.lab",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.RunPython(populate_student_ug_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("batch", "ug_number"),
                name="unique_student_ug_number_per_batch",
            ),
        ),
    ]
