# Generated by Codex on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_student_course_ready_fields"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="unique_student_ug_number_per_batch",
        ),
        migrations.AlterField(
            model_name="student",
            name="ug_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
