# Generated by Django 5.2.12 on 2026-04-05 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_initial'),
        ('trainers', '0002_remove_trainer_unique_trainer_per_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='trainers.trainer'),
        ),
    ]
