# Generated by Codex on 2026-04-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_default_course(apps, schema_editor):
    Batch = apps.get_model("batch", "Batch")
    Course = apps.get_model("batch", "Course")

    default_course, _ = Course.objects.get_or_create(
        name="JavaScript",
        certification="ITS",
    )
    Batch.objects.filter(course__isnull=True).update(course=default_course)


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("certification", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name", "certification"],
            },
        ),
        migrations.AlterField(
            model_name="batch",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="batch",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="batch.course",
            ),
        ),
        migrations.AddField(
            model_name="batch",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(assign_default_course, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="batch",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to="batch.course",
            ),
        ),
    ]
