# Generated by Django 5.2.12 on 2026-04-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_course_and_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
