# Generated by Django 5.0.6 on 2026-04-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_batch_deleted_at_batch_is_deleted_course_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
